mysql -uroot -proot < empldir/database/empldir.sql
ant undeploy
ant instrument
ant deploy
wget -P /home/student/ICAClinic/test --save-cookies cookies.txt --keep-session-cookies "http://localhost:8080/empldir/Login.jsp?Login=admin&Password=admin&FormAction=login&FormName=Login"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/Default.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/images/logo.gif"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/images/admin.gif"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/images/home.gif"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/favicon.ico"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/AdminMenu.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/Login.jsp?querystring=&ret_page=%2Fempldir%2FAdminMenu.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/Login.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/AdminMenu.jsp?Default.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/AdminMenu.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DepsGrid.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DepsRecord.jsp?dep_id=1&"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DepsRecord.jsp?name=Software0&FormName=deps&FormAction=update&dep_id=1&PK_dep_id=1"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DepsGrid.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DepsRecord.jsp?dep_id=1&"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DepsRecord.jsp?name=Software0&FormName=deps&FormAction=cancel&dep_id=1&PK_dep_id=1"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DepsGrid.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DepsRecord.jsp?dep_id=1&"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DepsRecord.jsp?name=Software0&FormName=deps&FormAction=cancel&dep_id=1&PK_dep_id=1"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DepsGrid.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DepsRecord.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DepsRecord.jsp?name=test&FormName=deps&FormAction=insert&dep_id=&PK_dep_id="
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DepsGrid.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/AdminMenu.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsGrid.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsRecord.jsp?emp_login=&name=&manmonth=&emp_id=4&"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsRecord.jsp?name=Zhiheng&title=Developer&emp_login=zhiheng&emp_password=zhiheng&emp_level=3&dep_id=1&address=&email=bobk%40company.com&work_phone=%28364%29+134-5411&home_phone=%28564%29+343-3367&cell_phone=&picture=bobk.jpg&FormName=emps&FormAction=delete&emp_id=4&PK_emp_id=4"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsRecord.jsp?name=Zhiheng&title=Developer&emp_login=zhiheng&emp_password=zhiheng&emp_level=3&dep_id=1&address=1&email=bobk%40company.com&work_phone=%28364%29+134-5411&home_phone=%28564%29+343-3367&cell_phone=&manmonth=1&picture=bobk.jpg&FormName=emps&FormAction=delete&emp_id=4&PK_emp_id=4"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsRecord.jsp?name=Zhiheng&title=Developer&emp_login=zhiheng&emp_password=zhiheng&emp_level=3&dep_id=1&address=test&email=bobk%40company.com&work_phone=%28364%29+134-5411&home_phone=%28564%29+343-3367&cell_phone=&picture=bobk.jpg&FormName=emps&FormAction=update&emp_id=4&PK_emp_id=4"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsGrid.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsRecord.jsp?emp_login=&name=&manmonth=&emp_id=3&"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsRecord.jsp?name=Jhih&title=Developer&emp_login=jhih&emp_password=jhih&emp_level=3&dep_id=1&address=xixi&email=bobk%40company.com&work_phone=%28364%29+134-5411&home_phone=%28564%29+343-3367&cell_phone=&picture=bobk.jpg&FormName=emps&FormAction=update&emp_id=3&PK_emp_id=3"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsGrid.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsRecord.jsp?emp_login=&name=&manmonth=&"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsRecord.jsp?name=Xinwei&title=aaa&emp_login=aaa&emp_password=aaa&emp_level=0&dep_id=2&address=aaa&email=aaa%40aaa.com&work_phone=111&home_phone=111&cell_phone=111&picture=&FormName=emps&FormAction=insert&emp_id=&PK_emp_id="
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsGrid.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsGrid.jsp?emp_login=ali&name=&manmonth=0"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsGrid.jsp?emp_login=aaa&name=&manmonth=0"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsRecord.jsp?emp_login=aaa&name=&manmonth=0&emp_id=10&"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsRecord.jsp?name=Xinwei&title=aaa&emp_login=aaa&emp_password=aaa&emp_level=0&dep_id=2&address=aaa&email=aaa%40aaa.com&work_phone=111&home_phone=111&cell_phone=111&picture=&FormName=emps&FormAction=delete&emp_id=10&PK_emp_id=10"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsRecord.jsp?name=Xinwei&title=aaa&emp_login=aaa&emp_password=aaa&emp_level=0&dep_id=2&address=aaa&email=aaa%40aaa.com&work_phone=111&home_phone=111&cell_phone=111&picture=&FormName=emps&FormAction=cancel&emp_id=10&PK_emp_id=10"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsGrid.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsGrid.jsp?emp_login=aaa&name=&manmonth="
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsRecord.jsp?emp_login=aaa&name=&manmonth=&emp_id=10&"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsRecord.jsp?name=Xinwei&title=aaa&emp_login=aaa&emp_password=aaa&emp_level=0&dep_id=2&address=aaabbb&email=aaa%40aaa.com&work_phone=111&home_phone=111&cell_phone=111&picture=&FormName=emps&FormAction=update&emp_id=10&PK_emp_id=10"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpsGrid.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/Default.jsp"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpDetail.jsp?name=&dep_id=&email=&emp_id=2&"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/images/emps/lij.jpg"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpDetail.jsp?FormName=Record&FormAction=cancel&Trn_dep_id=&Trn_name=&Trn_email=&PK_emp_id=2"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/Default.jsp?dep_id=&name=&email="
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpDetail.jsp?name=&dep_id=&email=&emp_id=1&"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpDetail.jsp?FormName=Record&FormAction=cancel&Trn_dep_id=&Trn_name=&Trn_email=&PK_emp_id=1"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/Default.jsp?dep_id=&name=&email="
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpDetail.jsp?name=&dep_id=&email=&emp_id=10&"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpDetail.jsp?FormName=Record&FormAction=cancel&Trn_dep_id=&Trn_name=&Trn_email=&PK_emp_id=10"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/Default.jsp?dep_id=&name=&email="
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/Default.jsp?dep_id=&name=test&email="
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/Default.jsp?dep_id=&name=xinwei&email="
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpDetail.jsp?name=xinwei&dep_id=&email=&emp_id=10&"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/EmpDetail.jsp?FormName=Record&FormAction=cancel&Trn_dep_id=&Trn_name=xinwei&Trn_email=&PK_emp_id=10"
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/Default.jsp?dep_id=&name=xinwei&email="
wget -P /home/student/ICAClinic/test --load-cookies cookies.txt "http://localhost:8080/empldir/DumpServlet.jsp"
wget -P /home/student/ICAClinic/test localhost:8080/empldir/DumpServlet.jsp
ant report
